# Generated by Django 3.1.5 on 2021-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plates', 'Plates'), ('cardio', 'Cardio'), ('barbells', 'BarBells'), ('dumbbells', 'DumbBells'), ('benches', 'Benches'), ('sup', 'Supplementary'), ('rollers', 'Rollers'), ('mats', 'Mats'), ('band', 'Bands'), ('sbs', 'Straps, Belts and Support')], max_length=50),
        ),
    ]
