# Generated by Django 3.1.5 on 2021-06-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cs',
        ),
    ]
