# Generated by Django 3.1.5 on 2021-06-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210625_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='category',
        ),
    ]
